import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { getMovie } from "@/functions/request";
import { type NextPage } from "next";
import { useEffect, useState } from "react";

const Home: NextPage = ({}) => {
  const [topratedMovie, setTopratedMovie] = useState();
  const [discoverMovie, setDiscoverMovie] = useState([]);

  useEffect(() => {
    getMovie("/discover/movie")
    .then((res) => (
      setDiscoverMovie(res.results)
    ))
  }, []);

  return (
    <>
      <Head>
        <title>Rotten tomateoes</title>
        <meta name="description" content="Generated by Nextjs"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="min-h-screen bg-gray-800">
        <div className="h-[50vh] w-full bg-white">
          <div className="mx-auto h-full max-w-4xl">
            <nav className="flex items-center justify-between py-3">
              <h4 className=" text-xl font-bold text-red-500"> RT</h4>
              <div className="flex items-center space-x-2 space-x-2min-h-screen text-sm text-gray-700">
                <Link href="">ABOUT US</Link>
                <Link href="/login">LOGIN/REGISTER</Link>
              </div>
            </nav>

            {/* Hero Section */}
            <div className="flex  gap-x-10 lg:mt-20">
              <div className="relative h-80 w-60 flex-none rounded-lg">
                <Image
                  className="rounded-xl"
                  alt="Movie image"
                  src="/index.jpg"
                  fill
                />
              </div>
              <div className="space-y-4">
                <p className="text-xs">2021</p>
                <h4 className="text-5xl font-bold">NAME</h4>
                <small>Action</small>
                <p className="w-96 text-xs text-gray-800">
                  Overview
                </p>
                <div></div>
              </div>
            </div>
          </div>
        </div>

        <section className="mx-auto mt-56 h-full w-full max-w-4xl py-12">
          <div className="grid h-full grid-cols-4 gap-x-4 gap-y-8">
            {discoverMovie
              .map((movie) => (
                <Link href={"/movie/" + movie.id}>
                  <MovieList rating={movie.rating} title={movie.title} image={movie.poster_path} genre={movie.genre} duration={movie.duration}/>
                </Link>
              ))}
          </div>
        </section>
        <footer>
          <p className="py-4 text-center text-sm font-semibold uppercase text-gray-300">
            By Survivors
          </p>
        </footer>
      </main>
    </>
  );
};

export default Home;

function MovieList({ image, title, rating, duration, genre}) {
  return (
    <div className="text-sm font-semibold text-gray-100">
      <div className="relative h-72 w-full flex-none rounded-lg">
        <Image
          className="rounded-xl"
          alt="Movie image"
          src={"https://image.tmdb.org/t/p/w500/" + image}
          fill
        />
      </div>
      <div className="mt-2 space-y-1">
        <p>{title}</p>
        <div className="mt-2 space-y-1">
          <p>{duration} | {genre}</p>
          <small>{rating*10}%</small>
        </div>
      </div>
    </div>
  );
}