import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { getMovie } from "@/functions/request";
import { RoleEnum } from "@/functions/role.enum";
import { type NextPage } from "next";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { Interface } from "readline";

const Home: NextPage = ({ user }) => {

  interface movie {
    poster_path? : String;
    adult? : boolean;
    overview? : String;
    release_date? : String;
    id? : number;
    vote_average? : number;
    title? : String;
    popularity? : number;
    genre_ids? : number[];
  }

  const [topratedMovie, setTopratedMovie] = useState<movie[]>([]);
  const [discoverMovie, setDiscoverMovie] = useState([]);

  const router = useRouter();
  const { movieId } = router.query;

  useEffect(() => {
    getMovie("/discover/movie")
    .then((res) => (
      setDiscoverMovie(res.results)
    ))

    getMovie("/movie/top_rated")
    .then((res) => {
      setTopratedMovie(res.results);
      console.log(res.results);
    })
  }, []);

  if(!topratedMovie[0]) {
    return <div className='w-full h-screen flex items-center justify-center'>
      <p className='text-center'>Loading...</p>
    </div>
  }

  return (
    <>
      <Head>
        <title>Rotten tomateoes</title>
        <meta name="description" content="Generated by Nextjs"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className="min-h-screen bg-gray-800">
        <div className="h-[60vh] w-full bg-white">
          <div className="mx-auto h-full max-w-4xl">
            <nav className="flex items-center justify-between py-3">
              <h4 className=" text-xl font-bold text-red-500"> RT</h4>
              <div className="flex items-center space-x-2 space-x-2min-h-screen text-sm text-gray-700">
                <Link href="">ABOUT US</Link>
                {user ? (
                  <Link href="/login">LOG OUT</Link>
                ) : (
                  <Link href="/register">LOG IN/REGISTER</Link>
                )}
              </div>
            </nav>

            {/* Hero Section */}
            <div className="flex  gap-x-10 lg:mt-20">
              <div className="relative h-80 w-60 flex-none rounded-lg">
                <div></div>
                <Image
                  className="rounded-xl"
                  alt="Movie image"
                  src={
                    "https://image.tmdb.org/t/p/w500/" + 
                    topratedMovie[0].poster_path
                  }
                  fill
                />
              </div>
              <div className="space-y-4">
                <p className="text-xs">{topratedMovie[0].release_date}</p>
                <h4 className="text-5xl font-bold">{topratedMovie[0].title}</h4>
                <small>Action</small>
                <p className="w-96 text-xs text-gray-800">
                  {topratedMovie[0].overview}
                </p>
                <small>Vote: {topratedMovie[0].vote_average*10}%</small>
              </div>
            </div>
          </div>
        </div>

        <section className="mx-auto mt-56 h-full w-full max-w-4xl py-12">
          <div className="grid h-full grid-cols-4 gap-x-4 gap-y-8">
            {discoverMovie
              .map((movie, index) => (
                <Link href="/movie/account">
                  <MovieList rating={movie.vote_average} title={movie.title} image={movie.poster_path} genre={movie.genres} duration={movie.runtime}/>
                </Link>
              ))}
          </div>
        </section>
        <footer>
          <p className="py-4 text-center text-sm font-semibold uppercase text-gray-300">
            By Survivors
          </p>
        </footer>
      </main>
    </>
  );
};

export default Home;

function MovieList({ image, title, rating, duration, genre}) {
  return (
    <div className="text-sm font-semibold text-gray-100">
      <div className="relative h-72 w-full flex-none rounded-lg">
        <Image
          className="rounded-xl"
          alt="Movie image"
          src={"https://image.tmdb.org/t/p/w500/" + image}
          fill
        />
      </div>
      <div className="mt-2 space-y-1">
        <p>{title}</p>
        <div className="mt-2 space-y-1">
          <p>120 min | ACTION</p>
          <small>Vote: {rating*10}%</small>
        </div>
      </div>
    </div>
  );
}