import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { type NextPage } from "next";
import { useState } from "react";

const Home: NextPage = ({}) => {
    const [rating, setRating] = useState<number>(0);
    const [comment, setComment] = useState<string>("");
    const [movieData, setMovieData] = useState(null); 
    const [actorList, setActorList] = useState([]);
    
    function onChangeComment() {
    }

    function onChangeRate() {
    }

    return (
      <>
        <Head>
          <title>Rotten tomateoes</title>
          <meta name="description" content="Generated by Nextjs"/>
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <main className="min-h-screen bg-gray-800">
          <div className="h-[50vh] w-full bg-white">
            <div className="mx-auto h-full max-w-4xl">
              <nav className="flex items-center justify-between py-3">
                <h4 className=" text-xl font-bold text-red-500"> RT</h4>
                <div className="flex items-center space-x-2 space-x-2min-h-screen text-sm text-gray-700">
                  <Link href="">ABOUT US</Link>
                  <Link href="/login">LOGOUT</Link>
                </div>
              </nav>

              {/* Hero Section */}
              <div className="flex  gap-x-10 lg:mt-20">
                <div className="relative h-80 w-60 flex-none rounded-lg">
                  <Image
                    className="rounded-xl"
                    alt="Movie image"
                    src="/index.jpg"
                    fill
                  />
                </div>
                <div className="space-y-4">
                  <p className="text-xs">2021</p>
                  <h4 className="text-5xl font-bold">NAME</h4>
                  <small>Action</small>
                  <p className="w-96 text-xs text-gray-800">
                    Overview
                  </p>
                  <div></div>
                </div>
              </div>
              <form className="mt-12">
                <div className="flex items-center justify-between">
                </div>
                <textarea
                  onChange={onChangeComment}
                  name=""
                  id=""
                  cols={20}
                  rows={5}
                  className="w-full appearance-none rounded-xl bg-gray-500 p-1  text-gray-100 outline-none focus-within:ring-gray-900 focus-within:ring-offset-1 focus-within:ring-offset-transparent focus:ring-4"
                ></textarea>
                <div className="flex justify-end">
                  <button className="ml mt-4 rounded-lg bg-red-800 px-3 py-1.5 font-semibold text-red-100">
                    Commenter
                  </button>
                </div>
              </form>
            </div>
          </div>

          <section className="mx-auto mt-60 h-full w-full max-w-4xl py-20">
            <div className="grid h-full grid-cols-4 gap-x-4 gap-y-8">
              <MovieList/>
              <MovieList/>
              <MovieList/>
              <MovieList/>
            </div>
          </section>
          <footer>
            <p className="py-4 text-center text-sm font-semibold uppercase text-gray-300">
              By Survivors
            </p>
          </footer>
        </main>
      </>
    );
};  

export default Home;

function MovieList({}) {
  return (
    <div className="text-sm font-semibold text-gray-100">
      <div className="mt-20 relative h-72 w-full flex-none rounded-lg">
        <Image
          className="rounded-xl"
          alt="Movie image"
          src="/index.jpg"
          fill
        />
      </div>
      <div className="mt-2 space-y-1">
        <p>NAME</p>
        <div className="mt-2 space-y-1">
          <p>120 min | ACTION</p>
          <small>100%</small>
        </div>
      </div>
    </div>
  );
}